// Code generated by MockGen. DO NOT EDIT.
// Source: price_repository.go

// Package repositories is a generated GoMock package.
package repositories

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIPriceRepository is a mock of IPriceRepository interface.
type MockIPriceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPriceRepositoryMockRecorder
}

// MockIPriceRepositoryMockRecorder is the mock recorder for MockIPriceRepository.
type MockIPriceRepositoryMockRecorder struct {
	mock *MockIPriceRepository
}

// NewMockIPriceRepository creates a new mock instance.
func NewMockIPriceRepository(ctrl *gomock.Controller) *MockIPriceRepository {
	mock := &MockIPriceRepository{ctrl: ctrl}
	mock.recorder = &MockIPriceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPriceRepository) EXPECT() *MockIPriceRepositoryMockRecorder {
	return m.recorder
}

// GetPrice mocks base method.
func (m *MockIPriceRepository) GetPrice(exchange, pair string) (*Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrice", exchange, pair)
	ret0, _ := ret[0].(*Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrice indicates an expected call of GetPrice.
func (mr *MockIPriceRepositoryMockRecorder) GetPrice(exchange, pair interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrice", reflect.TypeOf((*MockIPriceRepository)(nil).GetPrice), exchange, pair)
}
